import os
import sys

def resource_path(relative_path):
    """Obtém o caminho absoluto do recurso, ajustado para executáveis criados com PyInstaller."""
    if hasattr(sys, "_MEIPASS"):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath("."), relative_path)

# Defina os caminhos centralizados aqui
caminhos = {
    "icone": resource_path("imagens/icone.ico"),
    "aba_pedagogico": resource_path('imagens/aba_pedagogico.png'),
    "aba_relatorios" : resource_path('imagens/aba_relatorios.png'),
    "aba_arquivo" : resource_path('imagens/aba_arquivo.png'),
    "relatorios_pedagogico" : resource_path('imagens/relatorios_pedagogico.png'),
    "abrir_presencas_e_faltas" : resource_path('imagens/abrir_presencas_e_faltas.png'),
    "abrir_controle_pedagogico" : resource_path('imagens/abrir_controle_pedagogico.png'),
    "controle_pedagogico" : resource_path('imagens/controle_pedagogico.png'),
    "ocultar_contrato" : resource_path('imagens/ocultar_contrato.png'),
    "mostrar_icone_filtro_sala" : resource_path('imagens/mostrar_icone_filtro_sala.png'),
    "icone_filtro" : resource_path('imagens/icone_filtro.png'),
    "filtro_todos" : resource_path('imagens/filtro_todos.png'),
    "botao_fechar" : resource_path('imagens/botao_fechar.png'),
    "print_verificacao": resource_path('imagens/print_verificaçao.png'),
    "aba_anexar": resource_path('imagens/aba_anexar.png'),
    "abrir_planilha": resource_path('imagens/abrir_planilha.png'),
    "aluno_encontrado": resource_path('imagens/aluno_encontrado.png'),
    "anexar" : resource_path('imagens/anexar.png'),
    "tela_login" : resource_path('imagens/tela_login.png'),
    "hub_encontrado" : resource_path('imagens/hub_encontrado.png'),
    "hub_aberto" : resource_path('imagens/hub_aberto.png'),
    "caixa_mensagem" : resource_path('imagens/caixa_mensagem.png'),
    "campo_nome_planilha" : resource_path('imagens/campo_nome_planilha.png'),
    "campo_pesquisa" : resource_path('imagens/campo_pesquisa.png'),
    "contato_inexistente" : resource_path('imagens/contato_inexistente.png'),
    "contato" : resource_path('imagens/contato.png'),
    "contratos" : resource_path('imagens/contratos.png'),
    "contrato_aberto" : resource_path('imagens/contrato_aberto.png'),
    "descricao" : resource_path('imagens/descricao.png'),
    "exportar" : resource_path('imagens/exportar.png'),
    "exportar_documento" : resource_path('imagens/exportar_documento.png'),
    "documento_excel" : resource_path('imagens/documento_excel.png'),
    "botao_ok" : resource_path('imagens/botao_ok.png'),
    "adicionar_filtro" : resource_path('imagens/adicionar_filtro.png'),
    "nome_filtro_presencas" : resource_path('imagens/nome_filtro_presencas.png'),
    "nome_filtro_aluno" : resource_path('imagens/nome_filtro_aluno.png'),
    "valor_filtro" : resource_path('imagens/valor_filtro.png'),
    "abrir_menu_presencas" : resource_path('imagens/abrir_menu_presencas.png'),
    "abrir_menu_aluno" : resource_path('imagens/abrir_menu_aluno.png'),
    "abrir_menu_horas" : resource_path('imagens/abrir_menu_horas.png'),
    "ordem_ascendente" : resource_path('imagens/ordem_ascendente.png'),
    "editor_de_filtro" : resource_path('imagens/editor_de_filtro.png'),
    "construtor_filtro" : resource_path('imagens/construtor_filtro.png'),
    "filtrar_por_sala" : resource_path('imagens/filtrar_por_sala.png'),
    "filtrar_por_dias" : resource_path('imagens/filtrar_por_dias.png'),
    "filtrar_por_horas" : resource_path('imagens/filtrar_por_horas.png'),
    "contem" : resource_path('imagens/contem.png'),
    "abrir_faltas_por_periodo" : resource_path('imagens/abrir_faltas_por_periodo.png'),
    "faltas_por_periodo" : resource_path('imagens/faltas_por_periodo.png'),
    "fotos_e_videos" : resource_path('imagens/fotos_e_videos.png'),
    "imagem" : resource_path('imagens/imagem.png'),
    "lista_faltosos" : resource_path('imagens/lista_faltosos.png'),
    "logo" : resource_path('imagens/logo.png'),
    "menu_iniciar" : resource_path('imagens/menu_iniciar.png'),
    "nova_conversa" : resource_path('imagens/nova_conversa.png'),
    "ocorrencia" : resource_path('imagens/ocorrencia.png'),
    "opcoes_exportacao" : resource_path('imagens/opcoes_exportacao.png'),
    "pesquisa_aluno" : resource_path('imagens/pesquisa_aluno.png'),
    "pesquisa_contato" : resource_path('imagens/pesquisa_contato.png'),
    "pesquisar" : resource_path('imagens/pesquisar.png'),
    "abrir_presencas_e_faltas" : resource_path('imagens/abrir_presencas_e_faltas.png'),
    "presencas_e_faltas" : resource_path('imagens/presencas_e_faltas.png'),
    "salvar" : resource_path('imagens/salvar.png'),
    "substituir_arquivo" : resource_path('imagens/substituir_arquivo.png'),
    "visu_presencas_e_faltas" : resource_path('imagens/visu_presencas_e_faltas.png'),
    "visualizar" : resource_path('imagens/visualizar.png'),
    "msg_processo_finalizado":resource_path('imagens/msg_processo_finalizado.png'),
    "whatsapp_aberto" : resource_path('imagens/whatsapp_aberto.png'),
    "whatsapp_encontrado":resource_path('imagens/whatsapp_encontrado.png'),
    "historicos": resource_path("scripts/historicos.py"),
    "mensagens": resource_path("scripts/mensagens.py"),
    "planilhas": resource_path("scripts/planilhas.py"),
    "ocr": resource_path("scripts/ocr.py"),
    "bot": resource_path("bot.py")
    # Adicione outros caminhos necessários
}
